# TODO: Reconfigure to single buildpack step (compile + nginx + static)
steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cat <<EOF > src/environments/environment.prod.ts
        export const environment = {
          production: true,
          stsServer: '$_STS_SERVER',
          serverUrl: '$_API_SERVER',
          storageUrl: 'https://storage.googleapis.com/oos-images-63325/'
        };
        EOF
  - name: 'gcr.io/cloud-builders/yarn'
    args: [ 'build:prod' ]
  # Build the container image
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    env:
      - "TMPDIR=/builder/home/.pack"
    args:
      - build
      - gcr.io/$PROJECT_ID/oos-frontend:$SHORT_SHA
      - --cache-image=gcr.io/$PROJECT_ID/oos-frontend:cache
      - --builder=paketobuildpacks/builder:base
      # TODO: after nginx/staticfile buildpack fix revert to using latest version
      # - --buildpack=paketo-buildpacks/nginx
      - --buildpack=docker:///gcr.io/paketo-buildpacks/nginx:0.5.3
      - --buildpack=paketo-community/staticfile
      - --path=dist/
      - --publish
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - gcr.io/$PROJECT_ID/oos-frontend:$SHORT_SHA
      - --region
      - $_REGION
      - --platform
      - managed
      - --ingress
      - internal-and-cloud-load-balancing
      - --allow-unauthenticated
      - --service-account
      - $_SERVICE_ACCOUNT
      - --cpu=1
      - --memory=128Mi
      - --max-instances=4
      - --concurrency=40
      # Disable http2 because prod will be http1.1 for now
      - --no-use-http2
  # Clean old versions except previous Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - for revision in `gcloud run revisions list --service $_SERVICE_NAME --platform managed --region $_REGION --format 'value(name)' | sort -r | tail -n +3 | paste -sd " " -`; do $(yes | gcloud run revisions delete --platform managed --region $_REGION $revision) || exit 0; done;
