steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cat <<EOF > /root/.kube/config
      $$KUBECFG
      EOF
    secretEnv: ['KUBECFG']
    volumes:
    - name: 'kube'
      path: /root/.kube
  - name: alpine/helm:3.11.3
    env:
    - KUBECONFIG=/root/.kube/config
    args:
    - upgrade
    - --install
    - --values=./values.yaml
    - --set=image.fullTagOverride=$_IMAGE_TAG
    - --set=ingress.hosts[0].host=$_HOST
    - --set=ingress.tls[0].hosts[0]=$_HOST
    - --wait
    - frontend
    - https://github.com/ita-social-projects/OoS-Backend/raw/4b0a75827dee0f8119100705fbff091fac3e0c1d/k8s/infrastructure/charts/webapp-1.0.3.tgz
    volumes:
    - name: 'kube'
      path: /root/.kube
availableSecrets:
  secretManager:
  - versionName: $_KUBE_CONFIG
    env: 'KUBECFG'
options:
  pool:
    name: $_POOL
