steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cat <<EOF > /root/.kube/config
      $$KUBECFG
      EOF
    secretEnv: ['KUBECFG']
    volumes:
    - name: 'kube'
      path: /root/.kube
  - name: bitnami/kubectl
    env:
    - KUBECONFIG=/root/.kube/config
    args:
    - get
    - pod
    volumes:
    - name: 'kube'
      path: /root/.kube
availableSecrets:
  secretManager:
  - versionName: $_KUBE_CONFIG
    env: 'KUBECFG'
options:
  pool:
    name: $_POOL
