export enum CategoryIcons {  
  'assets/icons/icon_music.png' = 1,  
  'assets/icons/icon_dancing.png' = 2,
  'assets/icons/icon_sport.png' = 3,
  'assets/icons/icon_books.png' = 4,
  'assets/icons/icon_camera.png' = 5,
  'assets/icons/icon_construction.png' = 6,
  'assets/icons/icon_development.png' = 7,
  'assets/icons/icon_ecology.png' = 8,
  'assets/icons/icon_gardening.png' = 9,
  'assets/icons/icon_handmade.png' = 10,
  'assets/icons/icon_health.png' = 11,
  'assets/icons/icon_it.png' = 12,
  'assets/icons/icon_language.png' = 13,
  'assets/icons/icon_more.png' = 14,
  'assets/icons/icon_painting.png' = 15,
  'assets/icons/icon_rehabilitation.png' = 16,
  'assets/icons/icon_science.png' = 17,
  'assets/icons/icon_scout.png' = 18,
  'assets/icons/icon_signing.png' = 19,
  'assets/icons/icon_technique.png' = 20,
  'assets/icons/icon_theatre.png' = 21,
  'assets/icons/icon_travel.png' = 22,
}