export enum CategoryIcons {
  'assets/icons/icon_technique.svg' = 1,
  'assets/icons/icon_it.svg' = 2,
  'assets/icons/icon_camera.svg' = 3,
  'assets/icons/icon_handmade.svg' = 4,
  'assets/icons/icon_construction.svg' = 5,
  'assets/icons/icon_music.svg' = 6,
  'assets/icons/icon_signing.svg' = 7,
  'assets/icons/icon_dancing.svg' = 8,
  'assets/icons/icon_theatre_movie.svg' = 9,
  'assets/icons/icon_painting.svg' = 10,
  'assets/icons/icon_gardening.svg' = 11,
  'assets/icons/icon_ecology.svg' = 12,
  'assets/icons/icon_travel.svg' = 13,
  'assets/icons/icon_more.svg' = 14,
  'assets/icons/icon_science.svg' = 15,
  'assets/icons/icon_scout.svg' = 16,
  'assets/icons/icon_sport.svg' = 17,
  'assets/icons/icon_books.svg' = 18,
  'assets/icons/icon_rehabilitation.svg' = 19,
  'assets/icons/icon_health.svg' = 20,
  'assets/icons/icon_language.svg' = 21,
  'assets/icons/icon_development.svg' = 0,
}
