export enum ModalConfirmationType {
  delete = 'delete',
  deleteTeacher = 'deleteTeacher',
  deleteProviderAdmin = 'deleteProviderAdmin',
  deleteProviderAdminDeputy = 'deleteProviderAdminDeputy',
  blockProviderAdmin = 'blockProviderAdmin',
  blockProviderAdminDeputy = 'blockProviderAdminDeputy',
  leaveWorkshop = 'leaveWorkshop',
  deleteChild = 'deleteChild',
  leavePage = 'leavePage',
  rate = 'rate',
  createApplication = 'createApplication',
  approveApplication = 'approveApplication',
  rejectApplication = 'rejectApplication',
  createProviderAdmin = 'createProviderAdmin',
  createProviderAdminDeputy = 'createProviderAdminDeputy',
}
export enum ModalConfirmationTitle {
  delete = 'ВИДАЛИТИ ГУРТОК',
  deleteChild = 'ВИЛУЧИТИ ДАНІ ПРО ДИТИНУ?',
  deleteTeacher = 'ВИЛУЧИТИ ДАНІ ПРО ВЧИТЕЛЯ',
  deleteProviderAdmin = 'ВИДАЛИТИ АДМІНІСТРАТОРА ГУРТКА',
  deleteProviderAdminDeputy = 'ВИДАЛИТИ ЗАСТУПНИКА ДИРЕКТОРА',
  blockProviderAdmin = 'БЛОКУВАТИ АДМІНІСТРАТОРА ГУРТКА',
  blockProviderAdminDeputy = 'БЛОКУВАТИ ЗАСТУПНИКА ДИРЕКТОРА',
  leaveWorkshop = 'ЗАЛИШИТИ ГУРТОК?',
  leavePage = 'ЗАЛИШИТИ СТОРІНКУ?',
  createApplication = 'ПОДАТИ ЗАЯВКУ?',
  approveApplication = 'ЗАРАХУВАТИ',
  rejectApplication = 'ВІДМОВИТИ',
  createProviderAdmin = 'ДОДАТИ АДМІНІСТРАТОРА ГУРТКА',
  createProviderAdminDeputy = 'ДОДАТИ ЗАСТУПНИКА ДИРЕКТОРА',
}

export enum ModalConfirmationText {
  delete = 'Ви впевнені, що хочете видалити гурток',
  deleteChild = 'Ви впевнені, що хочете вилучити дані про дитину',
  deleteTeacher = 'Ви впевнені, що хочете вилучити дані про вчителя ?',
  deleteProviderAdmin = 'Ви впевнені, що хочете видалити адміністратора гуртка',
  deleteProviderAdminDeputy = 'Ви впевнені, що хочете видалити заступника директора',
  blockProviderAdmin = 'Ви впевнені, що хочете блокувати адміністратора гуртка',
  blockProviderAdminDeputy = 'Ви впевнені, що хочете блокувати заступника директора',
  leaveWorkshop = 'Ви впевнені, що хочете залишити гурток',
  leavePage = 'Ви впевнені, що хочете залишити сторінку?',
  rate = 'Поставте будь ласка оцінку цьому гуртку',
  createApplication = 'Ви впевнені, що хочете подати заявку у гурток',
  approveApplication = 'Ви впевнені, що хочете перевести заявку в статус "Зарахувати"?',
  rejectApplication = 'Ви впевнені, що хочете перевести заяву у статус ”Відмовлено”?',
  createProviderAdmin = 'Ви впевнені, що хочете додати адміністратора гуртка?',
  createProviderAdminDeputy = 'Ви впевнені, що хочете додати заступника директора?',
}
