export enum NavBarName {
  MainPage = 'Головна',
  WorkshopResult = 'Результати пошуку',
  TopDestination = 'Найпопулярніші напрямки',
  Portal = 'Портал',
  AboutPortal = 'Про портал',
  SupportInformation = 'Підтримка',
  LawsAndRegulations = 'Нормативно правові акти',
  RequestOnWorkshop = 'Заява на гурток',
  PersonalInformation = 'Особиста інформація',
  InformationAboutChild = 'Інформація про дітей',
  AddInformationAboutChild = 'Додати дані про дитину',
  EditInformationAboutChild = 'Редагувати дані про дитину',
  EditInstitutions = 'Редагувати заклад',
  EditInformationAbout = 'Редагування особистої інформації',
  EditDirection = 'Редагування напрямку',
  CreateDirection = 'Додати напрямок',
  Platform = 'Портал',
  NewWorkshop = 'Новий гурток',
  EditWorkshop = 'Редагування гуртка',
  CreateProviderDeputy = 'Додати заступника директора',
  CreateProviderAdmin = 'Додати адміністратора гуртка',
  Applications = 'Заявки',
  Workshops = 'Мої гуртки',
  Favorite = 'Улюблені',
  UserInfo = 'Особиста інформація',
  Administration = 'Адміністрування',
  Children = 'Інформація про дитину',
  ProviderInfo = 'Інформація про заклад',
  Users = 'Користувачі',
  Providers = 'Заклади',
  Directions = 'Напрямки',
}
export enum PersonalCabinetTitle {
  admin = 'Кабінет тех.адміна',
  user = 'Кабінет користувача',
  provider = 'Кабінет надавача',
  parent = 'Кабінет користувача',
  ProviderDeputy = 'Кабінет заступника директора',
  ProviderAdmin = 'Кабінет адміністратора гуртка',
  None = 'Кабінет надавача',
}
