export enum NavBarName {
  MainPage = 'Головна',
  WorkshopResult = 'Результати пошуку',
  TopDestination = 'Найпопулярніші напрямки',
  PersonalCabinetParent = 'Кабінет користувача',
  PersonalCabinetProvider = 'Кабінет надавача',
  PersonalCabinetTechAdmin = 'Кабінет тех.адміна',
  AdminTools = 'Адміністрування',
  About = 'Про портал',
  Support = 'Підтримка',
  Rules = 'Правила користування',
  Direction = 'Напрямок',
  RequestOnWorkshop = 'Заява на гурток',
  PersonalInformation = 'Особиста інформація',
  InformationAboutChild = 'Інформація про дитину',
  AddInformationAboutChild = 'Додати дані про дитину',
  EditInformationAboutChild = 'Редагувати дані про дитину',
  EditInstitutions = 'Редагувати заклад',
  EditInformationAbout = 'Редагування особистої інформації',
  EditDirection = 'Редагування напрямку',
  Platform = 'Портал',
  NewWorkshop = 'Новий гурток',
  EditWorkshop = 'Редагування гуртка',
  CreateProviderAdmin = 'Створення користувача',
}
