export enum ValidationErrorsEnum {
  Required = 'required',
  InvalidValue = 'invalidValue',
  InvalidEmail = 'invalidEmail',
  MinNumberValue = 'minNumberValue',
  InvalidEmailType = 'invalidEmailType',
  InvalidSearch = 'invalidSearch',
  InvalidTimeFormat = 'invalidTimeFormat',
  InvalidPhoneLength = 'invalidPhoneLength',
  InvalidPhoneNumber = 'invalidPhoneNumber',
  InvalidEdrpouIpn = 'invalidEdrpouIpn',
  InvalidFieldLength = 'invalidFieldLength',
  InvalidAgeRange = 'invalidAgeRange',
  InvalidTimeRange = 'invalidTimeRange',
  IncorrectDateField = 'incorrectDateField',
  InvalidDateRange = 'invalidDateRange',
  InvalidSymbols = 'invalidSymbols',
  InvalidCharacters = 'invalidCharacters',
  InvalidStreet = 'invalidStreet',
  InvalidHouse = 'invalidHouse',
  InvalidSectionName = 'invalidSectionName',
  MustContainLetters = 'mustContainLetters',
  MatDatepickerParse = 'matDatepickerParse',
  MatDatepickerMax = 'matDatepickerMax',
  MatDatepickerMin = 'matDatepickerMin'
}
