export enum ApplicationChanges {
  'ENUM.APPLICATION_CHANGES.CHANGE_IN_STATEMENTS',
  'ENUM.APPLICATION_CHANGES.CHANGES_IN_STATEMENTS',
  'ENUM.APPLICATION_CHANGES.CHANGE_IN_STATEMENTS_ABLATIVE'
}

export enum ApplicationApproved {
  'ENUM.APPLICATION_APPROVED.APPLICATION_ACCEPTED',
  'ENUM.APPLICATION_APPROVED.APPLICATIONS_ACCEPTED',
  'ENUM.APPLICATION_APPROVED.APPLICATION_ACCEPTED_ABLATIVE'
}

export enum ApplicationPending {
  'ENUM.APPLICATION_PENDING.APPLICATION_PENDING_CONFIRMATION',
  'ENUM.APPLICATION_PENDING.APPLICATIONS_PENDING_CONFIRMATION',
  'ENUM.APPLICATION_PENDING.CHANGE_IN_STATEMENTS_ABLATIVE'
}

export enum ApplicationRejected {
  'ENUM.APPLICATION_REJECTED.APPLICATION_REJECTED',
  'ENUM.APPLICATION_REJECTED.APPLICATIONS_REJECTED',
  'ENUM.APPLICATION_REJECTED.APPLICATION_REJECTED_ABLATIVE'
}

export enum ApplicationLeft {
  'ENUM.APPLICATION_LEFT.WORKSHOP_LEFT',
  'ENUM.APPLICATION_LEFT.WORKSHOPS_LEFT',
  'ENUM.APPLICATION_LEFT.WORKSHOP_LEFT_ABLATIVE'
}
