export enum NotificationsProviderShortDescriptions {
  Editing = 'NOTIFICATION_DETAILS.PROVIDER_SHORT_DESCRIPTION.EDITING',
  Approved = 'NOTIFICATION_DETAILS.PROVIDER_SHORT_DESCRIPTION.APPROVED',
  Block = 'NOTIFICATION_DETAILS.PROVIDER_SHORT_DESCRIPTION.BLOCK',
  Unblock = 'NOTIFICATION_DETAILS.PROVIDER_SHORT_DESCRIPTION.UNBLOCK',
}

export enum NotificationWorkshopShortDescription {
  Open = 'NOTIFICATION_DETAILS.WORKSHOP_SHORT_DESCRIPTION.OPEN',
  Closed = 'NOTIFICATION_DETAILS.WORKSHOP_SHORT_DESCRIPTION.CLOSED',
}

export enum NotificationProviderLicenseShortDescription {
  Approved = 'NOTIFICATION_DETAILS.LICENSE_SHORT_DESCRIPTION.APPROVED',
  Pending = 'NOTIFICATION_DETAILS.LICENSE_SHORT_DESCRIPTION.PENDING',
  NotProvided = 'NOTIFICATION_DETAILS.LICENSE_SHORT_DESCRIPTION.NOT_PROVIDED',
}

export enum NotificationsProviderFullDescriptions {
  Editing = 'NOTIFICATION_DETAILS.PROVIDER_FULL_DESCRIPTION.EDITING',
  Approved = 'NOTIFICATION_DETAILS.PROVIDER_FULL_DESCRIPTION.APPROVED',
  Block = 'NOTIFICATION_DETAILS.PROVIDER_FULL_DESCRIPTION.BLOCK',
  Unblock = 'NOTIFICATION_DETAILS.PROVIDER_FULL_DESCRIPTION.UNBLOCK',
}

export enum NotificationWorkshopFullDescriptions {
  Open = 'NOTIFICATION_DETAILS.WORKSHOP_FULL_DESCRIPTION.OPEN',
  Closed = 'NOTIFICATION_DETAILS.WORKSHOP_FULL_DESCRIPTION.CLOSED',
}

export enum NotificationProviderLicenseFullDescription {
  Approved = 'NOTIFICATION_DETAILS.LICENSE_FULL_DESCRIPTION.APPROVED',
  Pending = 'NOTIFICATION_DETAILS.LICENSE_FULL_DESCRIPTION.PENDING',
  NotProvided = 'NOTIFICATION_DETAILS.LICENSE_FULL_DESCRIPTION.NOT_PROVIDED',
}
