export enum ApplicationTitles {
  All = 'ENUM.APPLICATION_STATUSES.ALL',
  Pending = 'ENUM.APPLICATION_STATUSES.PENDING',
  Approved = 'ENUM.APPLICATION_STATUSES.APPROVED',
  Rejected = 'ENUM.APPLICATION_STATUSES.REJECTED',
  Left = 'ENUM.APPLICATION_STATUSES.LEFT',
  AcceptedForSelection = 'ENUM.APPLICATION_STATUSES.ACCEPTED_FOR_SELECTION',
  StudyingForYears = 'ENUM.APPLICATION_STATUSES.STUDYING_FOR_YEARS',
  Completed = 'ENUM.APPLICATION_STATUSES.COMPLETED',
  Blocked = 'ENUM.APPLICATION_STATUSES.BLOCKED',
  Banned = 'ENUM.APPLICATION_STATUSES.BANNED'
}

export enum ApplicationStatusDescription {
  Pending = 'ENUM.APPLICATION_DESCRIPTION.PENDING',
  AcceptedForSelection = 'ENUM.APPLICATION_DESCRIPTION.ACCEPTED_FOR_SELECTION',
  Approved = 'ENUM.APPLICATION_DESCRIPTION.APPROVED',
  StudyingForYears = 'ENUM.APPLICATION_DESCRIPTION.STUDYING_FOR_YEARS',
  Rejected = 'ENUM.APPLICATION_DESCRIPTION.REJECTED',
  Left = 'ENUM.APPLICATION_DESCRIPTION.LEFT',
  Completed = 'ENUM.APPLICATION_DESCRIPTION.COMPLETED',
  Blocked = 'ENUM.APPLICATION_DESCRIPTION.BLOCKED',
  Banned = 'ENUM.APPLICATION_DESCRIPTION.BANNED'
}

// Statuses for user Email Confirmation
export enum UserStatusesTitles {
  NeverLogged = 'ENUM.USER_STATUSES.NEVER_LOGGED',
  Accepted = 'ENUM.USER_STATUSES.ACCEPTED',
  Blocked = 'ENUM.USER_STATUSES.BLOCKED'
}

// Statuses for user Email Confirmation
export enum EmailConfirmationStatusesTitles {
  Pending = 'ENUM.EMAIL_CONFIRMATION_STATUSES.PENDING',
  Confirmed = 'ENUM.EMAIL_CONFIRMATION_STATUSES.CONFIRMED',
  NotConfirmed = 'ENUM.EMAIL_CONFIRMATION_STATUSES.NOT_CONFIRMED'
}

export enum ProviderStatusTitles {
  Approved = 'ENUM.PROVIDER_STATUSES.APPROVED',
  Pending = 'ENUM.PROVIDER_STATUSES.PENDING',
  Editing = 'ENUM.PROVIDER_STATUSES.EDITING',
  Blocked = 'ENUM.PROVIDER_STATUSES.BLOCK',
  Recheck = 'ENUM.PROVIDER_STATUSES.RECHECK'
}

export enum LicenseStatusTitles {
  Approved = 'ENUM.LICENSE_STATUSES.APPROVED',
  Pending = 'ENUM.LICENSE_STATUSES.PENDING',
  NotProvided = 'ENUM.LICENSE_STATUSES.NOT_PROVIDED'
}

export enum ProviderStatusDetails {
  Approved = 'ENUM.PROVIDER_STATUS_DETAILS.APPROVED',
  Pending = 'ENUM.PROVIDER_STATUS_DETAILS.PENDING',
  Blocked = 'ENUM.PROVIDER_STATUS_DETAILS.BLOCKED',
  BlockedPhoneNumber = 'ENUM.PROVIDER_STATUS_DETAILS.BLOCKED_PHONE_NUMBER',
  Editing = 'ENUM.PROVIDER_STATUS_DETAILS.EDITING',
  Recheck = 'ENUM.PROVIDER_STATUS_DETAILS.RECHECK'
}
