export enum PayRateTypeEnum {
  Classes = 'ENUM.PAY_RATE_TYPE.CLASS',
  Month = 'ENUM.PAY_RATE_TYPE.MONTH',
  Day = 'ENUM.PAY_RATE_TYPE.DAY',
  Year = 'ENUM.PAY_RATE_TYPE.YEAR',
  Hour = 'ENUM.PAY_RATE_TYPE.HOUR',
  Course = 'ENUM.PAY_RATE_TYPE.COURSE',
  AllPeriod = 'ENUM.PAY_RATE_TYPE.ALL_PERIOD'
}

export enum RecruitmentStatusEnum {
  RecruitmentOngoing = 'ENUM.RECRUITMENT_STATUS.RECRUITMENT_OPEN',
  RecruitmentStoped = 'ENUM.RECRUITMENT_STATUS.RECRUITMENT_CLOSED',
  Stop = 'ENUM.RECRUITMENT_STATUS.STOP',
  Open = 'ENUM.RECRUITMENT_STATUS.OPEN',
  Draft = 'ENUM.RECRUITMENT_STATUS.DRAFT'
}

export enum DetailsTabTitlesEnum {
  AboutWorkshop = 'TITLES.ABOUT_THE_WORKSHOP',
  AboutProvider = 'TITLES.ABOUT_THE_PROVIDER',
  Teachers = 'TITLES.TEACHERS',
  OtherWorkshops = 'TITLES.OTHER_WORKSHOPS_OF_THE_PROVIDER',
  Reviews = 'TITLES.REVIEWS',
  Achievements = 'TITLES.ACHIEVEMENTS',
  Workshops = 'TITLES.WORKSHOPS_OF_THE_PROVIDER'
}

export enum FormOfLearningEnum {
  Offline = 'ENUM.FORM_OF_LEARNING.OFFLINE',
  Online = 'ENUM.FORM_OF_LEARNING.ONLINE',
  Mixed = 'ENUM.FORM_OF_LEARNING.MIXED'
}

export enum SpecialNeedsTypeEnum {
  None = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.NONE',
  Hearing = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.HEARING',
  Speaking = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.SPEAKING',
  Sight = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.SIGHT',
  Intelligence = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.INTELLIGENCE',
  Musculoskeletal = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.MUSCULOSKELETAL',
  Retardation = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.SPECIAL_NEEDS_TYPE.RETARDATION'
}

export enum EducationalShiftEnum {
  First = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.EDUCATIONAL_SHIFT.FIRST',
  Second = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.EDUCATIONAL_SHIFT.SECOND'
}

export enum AgeCompositionEnum {
  SameAge = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.AGE_COMPOSITION.SAME_AGE',
  DifferentAge = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.AGE_COMPOSITION.DIFFERENT_AGE'
}

export enum CoverageEnum {
  School = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.COVERAGE.SCHOOL',
  City = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.COVERAGE.CITY',
  District = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.COVERAGE.DISTRICT',
  Region = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.COVERAGE.REGION',
  AllUkraine = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.COVERAGE.ALL_UKRAINE',
  International = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.COVERAGE.INTERNATIONAL'
}

export enum WorkshopTypeEnum {
  None = 'ENUM.WORKSHOP_SELECT_DESCRIPTION.WORKSHOP_TYPE.NONE'
}
