export enum PayRateTypeEnum {
  Classes = 'ENUM.PAY_RATE_TYPE.CLASS',
  Month = 'ENUM.PAY_RATE_TYPE.MONTH',
  Day = 'ENUM.PAY_RATE_TYPE.DAY',
  Year = 'ENUM.PAY_RATE_TYPE.YEAR',
  Hour = 'ENUM.PAY_RATE_TYPE.HOUR',
  Course = 'ENUM.PAY_RATE_TYPE.COURSE',
  AllPeriod = 'ENUM.PAY_RATE_TYPE.ALL_PERIOD'
}

export enum RecruitmentStatusEnum {
  RecruitmentOngoing = 'ENUM.RECRUITMENT_STATUS.RECRUITMENT_OPEN',
  RecruitmentStoped = 'ENUM.RECRUITMENT_STATUS.RECRUITMENT_CLOSED',
  Stop = 'ENUM.RECRUITMENT_STATUS.STOP',
  Open = 'ENUM.RECRUITMENT_STATUS.OPEN',
  Draft = 'ENUM.RECRUITMENT_STATUS.DRAFT'
}

export enum DetailsTabTitlesEnum {
  AboutWorkshop = 'TITLES.ABOUT_THE_WORKSHOP',
  AboutProvider = 'TITLES.ABOUT_THE_PROVIDER',
  Teachers = 'TITLES.TEACHERS',
  OtherWorkshops = 'TITLES.OTHER_WORKSHOPS_OF_THE_PROVIDER',
  Reviews = 'TITLES.REVIEWS',
  Achievements = 'TITLES.ACHIEVEMENTS',
  Workshops = 'TITLES.WORKSHOPS_OF_THE_PROVIDER'
}

export enum FormOfLearningEnum {
  Offline = 'ENUM.FORM_OF_LEARNING.OFFLINE',
  Online = 'ENUM.FORM_OF_LEARNING.ONLINE',
  Mixed = 'ENUM.FORM_OF_LEARNING.MIXED'
}
