export enum AdminsFormTitlesNew {
  ministryAdmin = 'ENUM.NAV_BAR_NAME.ADD_PROVIDER_MINISTRY_ADMIN',
  regionAdmin = 'ENUM.NAV_BAR_NAME.ADD_PROVIDER_REGION_ADMIN',
  areaAdmin = 'ENUM.NAV_BAR_NAME.ADD_PROVIDER_TERRITORIAL_ADMIN',
}

export enum AdminsFormTitlesEdit {
  ministryAdmin = 'ENUM.NAV_BAR_NAME.EDIT_PROVIDER_MINISTRY_ADMIN',
  regionAdmin = 'ENUM.NAV_BAR_NAME.EDIT_PROVIDER_REGION_ADMIN',
  areaAdmin = 'ENUM.NAV_BAR_NAME.EDIT_PROVIDER_TERRITORIAL_ADMIN',
}

export enum AdminRolesTitles {
  ministryAdmin = 'ENUM.ADMINISTRATORS.MINISTRY_ADMIN',
  regionAdmin = 'ENUM.ADMINISTRATORS.REGION_ADMIN',
  areaAdmin = 'ENUM.ADMINISTRATORS.TERRITORIAL_ADMIN',
}
