export enum HistoryLogTabTitles {
  Providers = 'ENUM.HISTORY_LOG.PROVIDERS',
  Employees = 'ENUM.HISTORY_LOG.EMPLOYEES',
  Applications = 'ENUM.HISTORY_LOG.APPLICATIONS',
  Users = 'ENUM.HISTORY_LOG.USERS'
}

export enum TypeChange {
  FullTitle = 'FORMS.LABELS.PROVIDER_TITLE',
  EdrpouIpn = 'FORMS.LABELS.EDRPO_IPN',
  Director = 'FORMS.LABELS.DIRECTOR_NAME',
  Institution = 'FORMS.LABELS.SUBORDINATION',
  LegalAddress = 'FORMS.HEADERS.LEGAL_ADDRESS',
  Status = 'HISTORY_LOG.STATUS_CHANGE_TYPE'
}

export enum AdminStatus {
  Create = 'ENUM.HISTORY_LOG.ADMIN_STATUS.CREATE',
  Update = 'ENUM.HISTORY_LOG.ADMIN_STATUS.UPDATE',
  Delete = 'ENUM.HISTORY_LOG.ADMIN_STATUS.DELETE',
  Block = 'ENUM.HISTORY_LOG.ADMIN_STATUS.BLOCK'
}
