export enum HistoryLogTabTitles {
  Providers = 'ENUM.HISTORY_LOG.PROVIDERS',
  ProviderAdmins = 'ENUM.HISTORY_LOG.ADMINS',
  Applications = 'ENUM.HISTORY_LOG.APPLICATIONS',
}


export enum TypeChange {
  FullTitle = 'FORMS.LABELS.PROVIDER_TITLE',
  EdrpouIpn = 'FORMS.LABELS.EDRPO_IPN',
  Director = 'FORMS.LABELS.DIRECTOR_NAME',
  Institution = 'FORMS.LABELS.SUBORDINATION',
  LegalAddress = 'FORMS.HEADERS.LEGAL_ADDRESS',
  Status = 'HISTORY_LOG.STATUS_CHANGE_TYPE'
}

export enum UserStatus {
  Create = 'ENUM.HISTORY_LOG.USER_STATUS.CREATE',
  Update = 'ENUM.HISTORY_LOG.USER_STATUS.UPDATE',
  Delete = 'ENUM.HISTORY_LOG.USER_STATUS.DELETE',
  Block = 'ENUM.HISTORY_LOG.USER_STATUS.BLOCK'
}
