name: Run tests

on:
  push:
    branches: [master, dev/*, feat/create-workflow]
  pull_request:
    branches: [master, dev/*, feat/create-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ng test