name: Run tests

on:
  push:
    branches: [master, develop, feat/create-workflow]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Run tests
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} 
          cmd: test # will run `yarn test` command
      
        
